sudo: false

language: scala

scala:
  - 2.10.5
  - 2.11.7

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

before_script: travis_retry sbt ++$TRAVIS_SCALA_VERSION update
script: sbt ++$TRAVIS_SCALA_VERSION coverage test
after_success: sbt coveralls
